[versions]
central = "1.2.8"
dokka = "2.0.0"
kotlin = "2.1.21"
ksp = "2.2.10-2.0.2"
publish = "1.3.1"

[libraries]
ksp = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }

[plugins]
central = { id = "cn.lalaki.central", version.ref = "central" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "publish" }
